### PR TITLE
Pr remove crap

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Review by AssassinTee — COMMENTED** [review]
https://stackoverflow.com/questions/987142/make-gitignore-ignore-everything-except-a-few-files

```
# Ignore Everything
*

# Not the gitignore obv
!.gitignore

# And not Maps
!*.map

# DON'T FORGET MY SUBDIRS
!*/
```

**Comment by ChillerDragon** [comment]
@AssassinTee thought about it. But this can be annoying in the future for stuff like .gitattributes and readme.txt in subdirectorys and so on. Also i have no idea how well that works with subdirectorys. If you want to go and test all of it and then maintain it go for it :)

**Comment by AssassinTee** [comment]
Do we want to have a whitelist or a blacklist here? I don't want that other people can push malicous software here, so I would go with whitelists.

As mentioned in the stackoverflow link the subdirs work with the `!*/` line.
We could add `!*.txt`, `!*.md` since I don't care about text documents.

I think a whitelist is easier because you get a notification on push that a file you want to push is ignored by the `.gitignore`

**Comment by ChillerDragon** [comment]
> I think a whitelist is easier because you get a notification on push that a file you want to push is ignored by a gitignore

Never noticed that. As far as I know ``git add`` ignores ignored files silently. Maybe via the github web interface.


I am afraid a whitelist can cause unpredictable headache since this repository is mainly used by people who are not very familiar with git.

**Comment by AssassinTee** [comment]
> As far as I know `git add` ignores ignored files silently

No it doesn't:
```
git add test.exe 
Die folgenden Pfade werden durch eine Ihrer ".gitignore" Dateien ignoriert:
test.exe
Verwenden Sie -f wenn Sie diese wirklich hinzufügen möchten.
```
tested on ubuntu on a new test-repo

**Comment by ChillerDragon** [comment]
@AssassinTee ah yes could reproduce. Probably caused by my bad habit of always using ``git add .``.

**Comment by ChillerDragon** [comment]
I mean go for the whitelist if you know what you are doing and think its better :)

**Comment by AssassinTee** [comment]
> @AssassinTee ah yes could reproduce. Probably caused by my bad habit of always using `git add .`.

even then you should get a message <.< oh it's silent then, lol

**Comment by ChillerDragon** [comment]
@AssassinTee you are probably right with the whitelist approach. It's just that I never used that and thus do not know what can go wrong. So I do not want to install that in a repository that is not mine first.

**Comment by AssassinTee** [comment]
Since this is a map-repository you shouldn't push too much crap in it except when you do it explicitly (why?). So I go with whitelist, but i will add `.txt` and `.md` files as you suggested. I think most people who use this repository don't know git very well and will push crap like "mapfixer.exe" on accident.

**Comment by ChillerDragon** [comment]
@AssassinTee well in this pr i ignored *.txt to keep the readme but disallow adding more. Idk i just wanted to clean up this mess a bit. Do what you want here. You are more related to this repo than i am.

**Comment by AssassinTee** [comment]
Yes, thank you for cleaning up ^^ I just want to prevent needing more cleanups

**Pull request merged**
